Full refactor of dashboard
KoalaBotUK/KoalaBotFrontend pull request #3
Opened 2021-01-01 15:07 UTC by winflag10

Added the dashboard refactor and integrated this with the django template system

2021-01-01 18:21 UTC, 3eak requested changes
Really impressive work! Very tidy and I love how simple the Dark mode functionality is.

Just got some minor syntax stuff that needs fixing before we get it merged. Perhaps I will raise an issue to have a linter check over some stuff during our Travis run or in the commits.

2021-01-01 18:21 UTC, 3eak commented on Pipfile
> +python_version = "3.7"
What's the difference between Pipfile and requirements.txt? Or do they essentially do the same thing?

2021-01-01 18:21 UTC, 3eak commented on frontend/static/hamburger.css
> +}
Add a new line at the end of the file

2021-01-01 18:21 UTC, 3eak commented on frontend/static/hamburger.css
> +.hamburger{
It's only syntax-ual - but add a space before your `{` in each class in css.

2021-01-01 18:21 UTC, 3eak commented on frontend/static/home.css
> +a{
Again, could you add a space before `{` in all classes in this css file too

2021-01-01 18:21 UTC, 3eak commented on frontend/static/home.js
> +}
new line at end of file

2021-01-01 18:21 UTC, 3eak commented on frontend/templates/home.html
> +</html>
new line at end of file

2021-01-01 18:26 UTC, 3eak commented
> A question for the follow up: Are we better off building a base page then extending it or making every feature a module and using include

@VirajShah18 this question might be better for someone a bit more experienced with Django?

2021-01-01 21:42 UTC, VirajShah18 commented
> A question for the follow up: Are we better off building a base page then extending it or making every feature a module and using include

In my opinion it would be cleaner to build a base page and then extend it as it's most likely that the pages for each cog will be very similar. For cases where we do need a feature in only some pages, then the best thing would be to create a module for that feature and include it.

2021-01-01 23:19 UTC, winflag10 commented on Pipfile
> +python_version = "3.7"
Not sure.. The pipfile was generated when I setup the venv

2021-01-02 14:06 UTC, 3eak commented on Pipfile
> +python_version = "3.7"
Could you not check in the Pipfile and Pipfile.lock in this PR?

Using Pipfile will supercede our requirements.txt file on Heroku.  If we are going to make the swap between these two it should be done in a seperate PR so it can more easily be traced down if it raises problems.

2021-01-02 15:24 UTC, 3eak requested changes
Just some final bits to fix (as well as the Pipfile)

2021-01-02 15:24 UTC, 3eak commented on frontend/static/home.js
> +function toggleDark(){
```suggestion
function toggleDarkMode(){
```

2021-01-02 15:24 UTC, 3eak commented on frontend/static/home.js
> +function toggleNav(){
```suggestion
function toggleFullNavigationBar(){
```

2021-01-02 15:34 UTC, 3eak approved these changes
nice work!

2021-01-02 15:35 UTC, merged