Expressjs
KoalaBotUK/KoalaBotFrontend pull request #53
Opened 2021-04-09 13:01 UTC by ChrisF999

Added the backend and a very simple example.

2021-04-09 13:42 UTC, 3eak requested changes

2021-04-09 13:42 UTC, 3eak commented on prisma/schema.prisma
> +  url      = "file:./KoalaBot/windows_Koala.db"
so if we inserted the production database here, it should all just figure itself out?

2021-04-09 13:42 UTC, 3eak commented on express/routes/verfied_email.js
> +});
can you add one more example of a post? to show how someone would add a new entry to a database?

2021-04-09 13:42 UTC, 3eak commented on prisma/schema.prisma
> +}
new line at end of file please :)

2021-04-09 13:42 UTC, 3eak commented on express/routes/verfied_email.js
> +const { Router } = require("express");
typo in the file name: `verified_email.js`

Could we just change this file to be called `verify.js` instead? As we would likely have a route for each cog and their backend calls.

2021-04-09 13:42 UTC, 3eak commented on express/express.js
> +});
Do we need this?

2021-04-09 13:45 UTC, ChrisF999 commented on prisma/schema.prisma
> +  url      = "file:./KoalaBot/windows_Koala.db"
As long as our schemas stays the same yeah that is just using one made the koala submodule but the link to any koala bot database should work

2021-04-09 13:46 UTC, ChrisF999 commented on prisma/schema.prisma
> +}
Fairly sure my formatter removed it let me change that

2021-04-09 13:48 UTC, ChrisF999 commented on express/express.js
> +});
nope

2021-04-09 13:48 UTC, ChrisF999 commented on express/routes/verfied_email.js
> +const { Router } = require("express");
Yeah the file can be called whatever and opps for the typo just fixed that

2021-04-09 13:48 UTC, ChrisF999 commented on express/routes/verfied_email.js
> +});
sure I can do that now

2021-04-09 20:00 UTC, 3eak requested changes
some minor typos

2021-04-09 20:00 UTC, 3eak commented on express/express.js
> +app.use("/", verfy);
typos on verify

2021-04-10 19:19 UTC, ChrisF999 commented
Ready for review

2021-04-10 20:43 UTC, 3eak requested changes
One final request

2021-04-10 20:43 UTC, 3eak commented on src/components/Dashboard.js
> +  React.useEffect(() => {
Can you import the `useEffect` hook at the top (similar to `useContext`).

Could you also comment out this function? (As it is just an example)

2021-04-10 20:51 UTC, 3eak approved these changes

2021-04-10 20:51 UTC, merged