new branch without eol chars
KoalaBotUK/KoalaBotFrontend pull request #9
Opened 2021-01-07 00:00 UTC by xjl98

The changelog.md from the KoalaBot written into a webpage.
Can be accessed with the address /cogs.

2021-01-07 10:44 UTC, 3eak requested changes
I've left some comments to fix up but as I have mentioned previously to you this page does not belong in the dashboard. It is useful - but it will be included as a doc page from the koalabot.uk homepage rather than a page in the dashboard.

Also - having to update this page every time we update KoalaBot is a bit long. Maybe it is worth us talking to the backend team for maintaining a CHANGELOG.json file or something for us to more easily parse the latest changes and automatically reflect them in the frontend.

2021-01-07 10:44 UTC, 3eak commented on frontend/static/cogs.css
> +}
add new line at end of file

2021-01-07 10:44 UTC, 3eak commented on frontend/templates/cogs.html
> +            <h4>Text Filter</h4>
Are we ordering this list by where they are in the CHANGELOG?

I think we should put the Base Cog at the top and display the extensions later.

The order would look like this:

LIST OF COGS
KoalaBot (Base) - commands
KoalaBot Extensions
list extensions with commands in any order ( TwitchAlert, TextFilter, RFR, ColourRole, Verify)

2021-01-07 13:34 UTC, xjl98 commented on frontend/templates/cogs.html
> +            <h4>Text Filter</h4>
I've added the changes, but yeah, I agree, it would be tedious to continuously update this page if we have to when new commands are added. 

I could bring this up with the backend team, but I don't think it's a huge priority right now.

2021-01-07 17:27 UTC, 3eak requested changes
some final little bits to fix

i'll discuss the json file with the backend team

2021-01-07 17:27 UTC, 3eak commented on frontend/templates/cogs.html
> +{% endblock %}
add new line at end of file

2021-01-07 17:27 UTC, 3eak commented on frontend/static/cogs.css
> +}
could we add a bit more space between the end of one cog extension to the title of the next cog extension (see below)
![Screenshot_54](https://user-images.githubusercontent.com/26631376/103923747-5eb0c580-510d-11eb-8402-f99c83a45c23.png)

2021-01-07 17:28 UTC, 3eak commented on frontend/templates/cogs.html
> +        <title>Koalabot | COGS</title>
```suggestion
        <title>Koalabot | Cogs </title>
```

2021-01-07 17:29 UTC, 3eak commented on frontend/static/cogs.css
> +}
Also - add more space or make 'List of Cogs' bigger here
![Screenshot_55](https://user-images.githubusercontent.com/26631376/103924369-d383ff80-510d-11eb-99f7-68ebb6c2b23b.png)

2021-01-07 19:03 UTC, xjl98 commented
I added the changes you've recommended - let me know if the spacing could be bigger.

There's one bug that I've encountered that I'm not sure how to fix, but the footer from the base.html template is positioned to the top right of the page for me. I think this may have been in previous commits as well, but I'm not absolutely sure.

2021-01-07 21:00 UTC, 3eak commented
> There's one bug that I've encountered that I'm not sure how to fix, but the footer from the base.html template is positioned to the top right of the page for me. I think this may have been in previous commits as well, but I'm not absolutely sure.

This is not present in [master](https://koala-staging.herokuapp.com/). And to my best knowledge I don't think this was in your previous commits.

2021-01-07 22:09 UTC, xjl98 commented
divs were messing up the positioning of the footer but it should be fine now.

2021-01-08 00:17 UTC, 3eak commented
Nice work - we'll park it here for now until we have the Koalabot.uk stuff set up in this repo and this page can find its' home.

2021-04-15 00:08 UTC, 3eak reviewed
I've rewritten and added some additional functionality.

~~Please see staged changes here: https://koala-staging2.herokuapp.com/~~

_Currently staging the heroku fix (#67)_

2021-04-19 19:20 UTC, ChrisF999 approved these changes

2021-04-19 19:27 UTC, stefan-cooper approved these changes

2021-04-19 19:27 UTC, merged